<?php

namespace AppBundle\Repository;

/**
 * HomepageSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
