<?php

namespace AppBundle\Repository;

/**
 * ImageCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
