<?php

namespace AppBundle\Repository;

/**
 * IngredientPreparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientPreparationRepository extends \Doctrine\ORM\EntityRepository
{
}
