<?php

namespace AppBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findIngredientsAutocomplete($term) {
        return $this->getEntityManager()
        ->createQuery('SELECT i FROM AppBundle:Ingredient i WHERE i.name LIKE :term ORDER BY i.name')
        ->setParameter("term", "%".$term."%")
        ->getResult();        
    }
}
