<?php

namespace AppBundle\Repository;

/**
 * IngredientPreparationListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientPreparationListRepository extends \Doctrine\ORM\EntityRepository
{
}
