<?php

namespace AppBundle\Repository;

/**
 * PreparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreparationRepository extends \Doctrine\ORM\EntityRepository
{
}
