<?php

namespace AppBundle\Repository;

/**
 * RecipeStepCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeStepCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
