<?php
namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFeaturedRecipes(int $n): array
    {
        $res1 = $this->getEntityManager()
            ->createQuery("SELECT r FROM AppBundle:Recipe r WHERE r.homepage_flag=TRUE ORDER BY r.creation_date DESC")
            ->setMaxResults($n)
            ->getResult();
        
        $res2 = $this->getEntityManager()
            ->createQuery("SELECT r FROM AppBundle:Recipe r ORDER BY r.creation_date DESC")
            ->setMaxResults($n)
            ->getResult();
        
        return array_slice(array_merge($res1, $res2), 0, $n);
    }
}
