<?php

namespace AppBundle\Repository;

/**
 * UnitOfMeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitOfMeasureRepository extends \Doctrine\ORM\EntityRepository
{
}
